global_variables:
    tracking_uri: "https://dagshub.com/JayJajoo/END_TO_END_MLOPS.mlflow"
training:
  random_state : 42
  hyper_params:
    n_estimators: [100, 200, 500]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.05, 0.1]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.7, 0.9, 1.0]
    gamma: [0, 1, 5]
    min_child_weight: [1, 3, 5]
    reg_lambda: [1, 10]
    reg_alpha: [0, 1]


    # MLFLOW_TRACKING_USERNAME: "JayJajoo"
    # MLFLOW_TRACKING_PASSWORD: "11de55f0dd6d99351121e2b1d59f58f4ac1db38a"
